// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:business_transactions/models/customer.dart';
import 'package:business_transactions/models/transaction.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CustomerAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CustomerAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}
